# Generated by Django 4.0.1 on 2022-02-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
